// Need to use the React-specific entry point to import `createApi`

import { createApi, fakeBaseQuery } from "@reduxjs/toolkit/query/react";
import { getProducts } from "./actions";

export const productsSlice = createApi({
  reducerPath: "Products",
  baseQuery: fakeBaseQuery(),
  endpoints: (builder) => ({
    getProducts: builder.query({
      queryFn: getProducts,
    }),
  }),
});

// Hooks are auto-generated by RTK-Query
// Same as `quotesApiSlice.endpoints.getQuotes.useQuery`
export const { useGetProductsQuery } = productsSlice;
