// Need to use the React-specific entry point to import `createApi`
// import { createClient } from "@/lib/supabase/client";
import { createApi, fakeBaseQuery } from "@reduxjs/toolkit/query/react";

// const supabase = createClient();
interface Product {
  id: number;
  name: string;
  author: string;
}

interface ProductsResponse {
  products: Product[];
  total: number;
  skip: number;
  limit: number;
}

// Define a service using a base URL and expected endpoints
export const productsSlice = createApi({
  baseQuery: fakeBaseQuery(),
  reducerPath: "products",
  // Tag types are used for caching and invalidation.
  tagTypes: ["Products"],
  endpoints: (builder) => ({
    // Supply generics for the return type (in this case `QuotesApiResponse`)
    // and the expected query argument. If there is no argument, use `void`
    // for the argument type instead.
    getProducts: builder.query({
      queryFn: async (category: string) => {
        const { data, error } = await supabase
          .from("products")
          .select(
            "id, name, photos, description, category, sub_category, in_stock"
          );

        if (error) {
          console.log(error);
          // throw { error };
        }
        console.log(data);
        return { data };
      },
      // `providesTags` determines which 'tag' is attached to the
      // // cached data returned by the query.
      providesTags: (result, error, id) => [{ type: "Products", id }],
    }),
  }),
});

// Hooks are auto-generated by RTK-Query
// Same as `quotesApiSlice.endpoints.getQuotes.useQuery`
export const { useGetProductsQuery } = productsSlice;
